### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by iMerica** [lamyfarai/react-typing-effect#15]
Hi,

Thanks for working on this. The source you've pushed to npm invokes `window` even though its not required and also not in the original source code. This prevents this library from being used in server-side rendered react projects like Next.js

You might want to build the source with Webpack instead of babel directly.

**Workaround**
Vendorize src/* into your local project. Use the library with a relative import.

**Comment by adambutler** [comment]
👍 Agree with above. I faced the same issue when trying to use this package with gatsby it would fail on building the static assets.

I've used @iMerica workaround but this should be easily avoidable by building with webpack.

**Comment by kiranvj** [comment]
@adambutler I had the same issue when I used the package with Gatsby. I did this work around 

File: \node_modules\react-typing-effect\dist\index.js

Added a check like this and it worked.

```
if(typeof window !== 'undefined') {
    // the entire file contents.
}
```

**Comment by adambutler** [comment]
Since the source doesn't use window only the output in `dist` it might be better to do what I and @iMerica have done.

Download the the project and place it into a `vendor` directory. Then you can import it as such:

```js
import ReactTypingEffect from "./vendor/react-typing-effect/src/lib";
```

This will be a little easier since when @lamyfarai releases a later version built with webpack then you can simply replace the import to:

```js
import ReactTypingEffect from "react-typing-effect";
```
